### ISSUE TITLE
[proposal] support cold page reclaim to improve memory overcommitment

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#1178]
**What is your proposal**:

In general colocation scenarios, the resources that the high-priority (HP) applications have requested but not used are reclaimable to the low-priority (LP) applications to allocate. Resource reclaiming helps enhance the utilization of machines while increasing the risks of contentions. For memory resources, there are proportions of memory that are reusable on different levels. The free memory is allocatable to any process, while the page cache is potentially reusable after it is reclaimed by the system and no longer yields again. The part of memory that is allocated but probably unused for a while is called the "cold" memory. Relatively, the memory which may be reclaimable but would be reallocated shortly after is the "hot" memory. To construct a more reliable and fine-grained memory overcommitment, the free and cold memory of the HP is preferred to reclaim to LP first. And if not required, the hot memory of HP should not be overcommitted, or the performance of HP can be affected.

In the Koordinator, we want to improve memory overcommitment by building the cold page reclaim ability, which can report the quantity of cold memory on the nodes and help assure that resource reclaiming like `batch-memory` are sound and efficient for the colocated applications. To build the ability, we should investigate open-sourced cold page reclaimers, select one or two alternatives to implement the cold memory collection and reporting in the koordlet, and identify them in the resource calculator of the koord-manager.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

Firstly, we expect to support the cold page reporting. (Planning in v1.4)

- [x] Propose the cold page reclaim solution. #1514 
- [x] Design the cold page reclaim API. #1561
- [x] Implement the cold page collection and reporting. #1574

Then we can use the cold page information to overcommit memory resources, support proactive memory reclaim strategy and improve load-aware scheduling.

- [x] Add the cold memory overcommitment for Batch resources. #1574, #1699
- [ ] Add the proactive memory reclaim strategy.
- [ ] Improve the load-aware scheduling with the cold memory info.

**Comment by BUPT-wxq** [comment]
```
/assign
```
