### ISSUE TITLE
[proposal] refactor `metric cache` module in `koordlet` with tsdb-type storage

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#1241]
**What is your proposal**:
refactor metric cache for better performance and expansibility.

**Why is this needed**:
metric cache is a module for metric data persistence in koordlet.

Currently, it use sqlite3 as the storage, which is an structured SQL-like database.
sqlite3 shows poor performance for time-series data like resource metrics, consuming more space and slow on query.
Besides, as an structured database, tables and interfaces must be added when adding new metrics on metric cache, which shows bad expansibility。

**Is there a suggested solution, if so, please add it**:
We plan to replace sqlite3 with tsdb for better performance and extension.

Followings are the detailed plan:
- [x] [build tsdb framework and interface in tsdb](https://github.com/koordinator-sh/koordinator/issues/586) @zwzhang0107 
- replace each metrics collect and query with tsdb interface
  - [x] [CPU throttled of pod/container](https://github.com/koordinator-sh/koordinator/pull/1228) @zwzhang0107 
  - [x] CPU/memory resource usage of pod/container @LambdaHJ
  - [x] [CPU/memory resource usage of node](https://github.com/koordinator-sh/koordinator/issues/1287) @LambdaHJ
  - [x] [performance resource(PSI/CPI) of pod/container](https://github.com/koordinator-sh/koordinator/issues/1329) @zshmmm
  - [x] [CPU/memory resource usage of different QoS (BE)](https://github.com/koordinator-sh/koordinator/issues/1450)
  - [x] [device resource(GPU) usage of node](https://github.com/koordinator-sh/koordinator/issues/1287) @LambdaHJ
  - [x] device resource(GPU) usage of pod/container @LambdaHJ
  - [x] [other info-type resource like cpuinfo, diskinfo (this may not needed with tsdb, but cache map)](https://github.com/koordinator-sh/koordinator/issues/1383) @LambdaHJ
- [ ] clean deprecated interfaces and structs
