### ISSUE TITLE
[proposal] Support resource reservation mechanism

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#188]
**What is your proposal**:

Support resource reservation mechanism.

**Why is this needed**:

There are some scenarios where this mechanism needs to be used:
- Preemption. Through the reservation mechanism, it can be guaranteed that Pods with the same priority must have resources available after preempting other Pods
- Descheduling. When descheduling, it is necessary to ensure that the descheduled Pod has resources available, which can better ensure the reliability of the application.
- Scaling. When the PaaS layer scaling replicas, it hopes to have a definite result, that is, whether there is enough capacity in the current cluster to expand new Pods.
- Reserve resources in advance. In some resource operation scenarios, some resources need to be reserved in advance to ensure future resource demands.

**Is there a suggested solution, if so, please add it**:
The support of resource reservation can be split into issues as follow:

1. [X] Propose the design of the reservation mechanism: #241 
2. [x] Define the Reservation API: #276 
3. [ ] Implement the reservation scheduling plugin.

**Comment by saintube** [comment]
The support of resource reservation can be split into issues as follow:

1. [X] Propose the design of the reservation mechanism: #241 
2. [ ] Define the Reservation API.
3. [ ] Implement the reservation scheduling plugin.
