### ISSUE TITLE
[proposal] Reservation support binding to scheduled pods

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#2150]
**What is your proposal**:

Besides reserving the unallocated node resources for further pods, reservations can match and bind to the scheduled pods on nodes.

**Why is this needed**:

Currently, the reservation can allocate the free node resources and reserve them for further pods (i.e. owners). In some advanced use cases, we want to keep a certain quantity of reserved resources in the cluster to ensure the resources are deterministic to deliver to users, so we reserve resources with reservations. Firstly, some user pods are scheduled and bound with reservations, and more pods are scheduled without any reservation. Once the user pods bound with reservations terminate, there are pods lacking reservations and reservations unbound to any pod. If we keep the unbound reservations, cluster resources are wasted. Otherwise, we clean up the unbound reservations, then the reserved resources are insufficient and the user pods are not assured to schedule deterministically.

For this case, we need the ability to let the reservation bind to scheduled pods. So when the reservations become unbound from the terminating pods, we can bind the reservations to other scheduled pods to keep the quantity of the reserved resources.

It also can be an alternative to the [*pre-allocation*](https://github.com/koordinator-sh/koordinator/blob/main/docs/proposals/scheduling/20220609-resource-reservation.md#usage-in-pre-allocation) mentioned in the reservation proposal. Reservation can first bind to a scheduled pod, and then the resources will be reserved after the pod terminates. It helps when the cluster resources are insufficient currently, but we want to pre-allocate resources for some pods to reschedule after the resources are ready.

**Is there a suggested solution, if so, please add it**:

This ability should be an option for a reservation object since not every reservation needs to bind scheduled pods.
It should support both unscheduled reservations and available reservations considering the pre-allocation scenarios.
The binding logic is recommended to implement in the koord-scheduler due to the consistency problem when new pods also could allocate the unbound reservations.

**Comment by saintube** [comment]
Patchset:
1. [x] Add the Pre-Allocation API. The controller supports fixing the pod annotation when the reservation terminates before the owner pod. #2513 
2. [x] The Reservation plugin supports Pre-Allocation workflow.
    - [x] Clear the ReservationAllocated of the owner pods when the available reservation is deleted. #2575
    - [x] PreFilter and Filter for pre-allocatable pods. #2571 
    - [x] Sort the pre-allocatable pods and nominate one of them to pre-allocate or allocate the node resources. #2592
    - [x] Reserve/Unreserve and PreBind the pre-allocation pod. #2592
    - [x] Disallow a reservation to pre-allocate multiple pods with one nomination. #2750
3. [x] Reservation-related plugins, e.g. Deviceshare, NodeNUMAResource, update the extension points for the Pre-Allocation.
    - [x] Plugins support to restore resources and allocate for pre-allocatable pods. #2744, #2752, #2757

**Comment by haosdent** [comment]
@saintube Thanks for your awesome work! Regarding the pre-allocation, would it introduce performance issues? Because when we filter node resources, we need to find all associated PreAllocation and re-calculate the remaining resources?

**Comment by saintube** [comment]
> [@saintube](https://github.com/saintube) Thanks for your awesome work! Regarding the pre-allocation, would it introduce performance issues? Because when we filter node resources, we need to find all associated PreAllocation and re-calculate the remaining resources?

Good point! Pre-allocation can indeed introduce some performance overhead, as it involves selecting scheduled pods for resource reservation. In the initial version, our focus is on providing basic functionality: binding reservations to a small set of specific pods to ensure resources are reserved even after those pods terminate. So, the pre-allocation is designed for specific use cases, and we need an efficient way to match pods to minimize overhead.

**Comment by haosdent** [comment]
Got it, thanks for your answer @saintube

**Comment by saintube** [comment]
/close
[All patches](https://github.com/koordinator-sh/koordinator/issues/2150#issuecomment-2650561213) have been merged. The pre-allocation will be released in v1.8.
